#include "pch.h"

#ifdef __BCPLUSPLUS__
#include <condefs.h>


//---------------------------------------------------------------------------
USEUNIT("3way.cpp");
USEUNIT("algebra.cpp");
USEUNIT("asn.cpp");
USEUNIT("base64.cpp");
USEUNIT("bench.cpp");
USEUNIT("bfinit.cpp");
USEUNIT("blowfish.cpp");
USEUNIT("blumgold.cpp");
USEUNIT("blumshub.cpp");
USEUNIT("camellia.cpp");
USEUNIT("cast.cpp");
USEUNIT("cast128s.cpp");
USEUNIT("crc.cpp");
USEUNIT("cryptlib.cpp");
USEUNIT("default.cpp");
USEUNIT("des.cpp");
USEUNIT("dessp.cpp");
USEUNIT("dh.cpp");
USEUNIT("diamond.cpp");
USEUNIT("diamondt.cpp");
USEUNIT("dsa.cpp");
USEUNIT("ec2n.cpp");
USEUNIT("eccrypto.cpp");
USEUNIT("ecp.cpp");
USEUNIT("elgamal.cpp");
USEUNIT("eprecomp.cpp");
USEUNIT("files.cpp");
USEUNIT("filters.cpp");
USEUNIT("forkjoin.cpp");
USEUNIT("gf2_32.cpp");
USEUNIT("gf256.cpp");
USEUNIT("gf2n.cpp");
USEUNIT("gost.cpp");
USEUNIT("gzip.cpp");
USEUNIT("haval.cpp");
USEUNIT("hex.cpp");
USEUNIT("idea.cpp");
USEUNIT("integer.cpp");
USEUNIT("iterhash.cpp");
USEUNIT("luc.cpp");
USEUNIT("md5.cpp");
USEUNIT("md5mac.cpp");
USEUNIT("misc.cpp");
USEUNIT("modes.cpp");
USEUNIT("nbtheory.cpp");
USEUNIT("oaep.cpp");
USEUNIT("pch.cpp");
USEUNIT("pkcspad.cpp");
USEUNIT("polynomi.cpp");
USEUNIT("pubkey.cpp");
USEUNIT("queue.cpp");
USEUNIT("rabin.cpp");
USEUNIT("randpool.cpp");
USEUNIT("rc5.cpp");
USEUNIT("ripemd.cpp");
USEUNIT("rng.cpp");
USEUNIT("rsa.cpp");
USEUNIT("safer.cpp");
USEUNIT("seal.cpp");
USEUNIT("secshare.cpp");
USEUNIT("secsplit.cpp");
USEUNIT("sha.cpp");
USEUNIT("shacal2.cpp");
USEUNIT("shark.cpp");
USEUNIT("sharkbox.cpp");
USEUNIT("square.cpp");
USEUNIT("squaretb.cpp");
USEUNIT("tea.cpp");
USEUNIT("test.cpp");
USEUNIT("tiger.cpp");
USEUNIT("tigertab.cpp");
USEUNIT("ttmac.cpp");
USEUNIT("validat1.cpp");
USEUNIT("validat2.cpp");
USEUNIT("validat3.cpp");
USEUNIT("wake.cpp");
USEUNIT("whrlpool.cpp");
USEUNIT("zbits.cpp");
USEUNIT("zdeflate.cpp");
USEUNIT("zinflate.cpp");
USEUNIT("ztrees.cpp");
USEUNIT("cbc.cpp");
USEUNIT("arc4.cpp");
USEUNIT("modexppc.cpp");
USEUNIT("md2.cpp");
USEUNIT("rc2.cpp");
USEUNIT("rc6.cpp");
USEUNIT("mars.cpp");
USEUNIT("rw.cpp");
USEUNIT("marss.cpp");
USEUNIT("nr.cpp");
USEUNIT("mqv.cpp");
USEUNIT("rijndael.cpp");
USEUNIT("twofish.cpp");
USEUNIT("serpent.cpp");
USEUNIT("rdtables.cpp");
USEUNIT("tftables.cpp");
USEUNIT("xtr.cpp");
USEUNIT("skipjack.cpp");
USEUNIT("mqueue.cpp");
USEUNIT("xtrcrypt.cpp");
USEUNIT("network.cpp");
USEUNIT("osrng.cpp");
USEUNIT("socketft.cpp");
//---------------------------------------------------------------------------
int cmain(int argc, char **argv);

int main(int argc, char **argv)
{
	return cmain(argc, argv);
}
#endif
